// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview AI-powered bio generator from Overleaf CV content.
 *
 * - generateAiBio - A function that generates an engaging 'About Me' paragraph from CV content.
 * - AiBioInput - The input type for the generateAiBio function.
 * - AiBioOutput - The return type for the generateAiBio function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AiBioInputSchema = z.object({
  cvContent: z
    .string()
    .describe('The content of the Overleaf CV, including technical facts, programming skills, and projects.'),
});
export type AiBioInput = z.infer<typeof AiBioInputSchema>;

const AiBioOutputSchema = z.object({
  bio: z.string().describe('A concise and engaging About Me paragraph.'),
});
export type AiBioOutput = z.infer<typeof AiBioOutputSchema>;

export async function generateAiBio(input: AiBioInput): Promise<AiBioOutput> {
  return generateAiBioFlow(input);
}

const prompt = ai.definePrompt({
  name: 'aiBioPrompt',
  input: {schema: AiBioInputSchema},
  output: {schema: AiBioOutputSchema},
  prompt: `You are a professional resume writer. You will be provided with the content of a CV, and your goal is to create a concise and engaging "About Me" paragraph that effectively highlights the candidate's unique traits, goals, and motivations to potential recruiters/collaborators.

CV Content: {{{cvContent}}}`,
});

const generateAiBioFlow = ai.defineFlow(
  {
    name: 'generateAiBioFlow',
    inputSchema: AiBioInputSchema,
    outputSchema: AiBioOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
