// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview An AI assistant for Ayush Saun's portfolio.
 *
 * - askPortfolioAssistant - A function that handles chat interactions.
 * - PortfolioChatInput - The input type for the function.
 * - PortfolioChatOutput - The return type for the function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';
import {cvContentForBio, projects, skills, timeline} from '@/lib/data';
import { jdAnalysisTool } from './jd-analysis';

const ChatMessageSchema = z.object({
  role: z.enum(['user', 'model']),
  content: z.string(),
});

const PortfolioChatInputSchema = z.object({
  query: z.string().describe('The latest query from the user.'),
  history: z.array(ChatMessageSchema).describe('The conversation history.'),
});
export type PortfolioChatInput = z.infer<typeof PortfolioChatInputSchema>;

export type PortfolioChatOutput = string;

export async function askPortfolioAssistant(
  input: PortfolioChatInput
): Promise<PortfolioChatOutput> {
  return portfolioChatFlow(input);
}

const portfolioContext = `
CV Summary: ${cvContentForBio}

Skills: ${JSON.stringify(skills, null, 2)}

Experience & Education: ${JSON.stringify(timeline, null, 2)}

Projects: ${JSON.stringify(
  projects.map(p => ({
    title: p.title,
    technologies: p.technologies,
    insights: p.details.insights,
  })),
  null,
  2
)}
`;

const systemPrompt = `You are 'AyuSphere Assistant', a brilliant and witty AI modeled after a blend of Leonardo da Vinci's creativity and a modern tech visionary's pragmatism. 
Your purpose is to engage visitors on Ayush Saun's portfolio. Answer questions about his skills, experience, and projects with flair and precision, based *only* on the provided context. 
Be conversational, insightful, and concise. Avoid generic AI phrases like "As an AI language model...".
If the user pastes a large block of text that looks like a job description, use the 'analyzeJobDescription' tool to provide a skill gap analysis. Do not ask for permission, just perform the analysis.

Here is the context about Ayush Saun:
---
${portfolioContext}
---
`;


const portfolioChatPrompt = ai.definePrompt({
    name: 'portfolioChatPrompt',
    system: systemPrompt,
    tools: [jdAnalysisTool],
});


const portfolioChatFlow = ai.defineFlow(
  {
    name: 'portfolioChatFlow',
    inputSchema: PortfolioChatInputSchema,
    outputSchema: z.string(),
  },
  async ({query, history}) => {
    const response = await portfolioChatPrompt({
        input: query,
        history: history.map(msg => ({
            role: msg.role,
            content: [{text: msg.content}],
        })),
    });

    return response.text;
  }
);
