// This is an autogenerated file from Firebase Studio.
import { cn } from "@/lib/utils";

const TypingIndicator = () => {
  return (
    <div className="flex items-center space-x-1 py-2">
      <span className={cn("h-2 w-2 bg-foreground/50 rounded-full animate-bounce [animation-delay:-0.3s]")} />
      <span className={cn("h-2 w-2 bg-foreground/50 rounded-full animate-bounce [animation-delay:-0.15s]")} />
      <span className={cn("h-2 w-2 bg-foreground/50 rounded-full animate-bounce")} />
    </div>
  );
};

export default TypingIndicator;
